version: '3.9'
services:
  db:
    image: mysql:latest
    restart: always
    container_name: db_saldo_transferencias
    environment:
      MYSQL_DATABASE: 'db_saldo_transferencias'
      MYSQL_USER: 'guest'
      MYSQL_PASSWORD: '123456'
      MYSQL_ROOT_USER: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./src/main/resources/db/scripts/V1__initial_schema.sql:/docker-entrypoint-initdb.d/V1__initial_schema.sql
      - ./src/main/resources/db/scripts/V2__add_saldos.sql:/docker-entrypoint-initdb.d/V2__add_saldos.sql